version: "1.1"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software.

services:
  prueba_django:
    # Imágen a utilizar:
    image: python:3.9.5
    # Nombre del container:
    container_name: prueba_djangoISDM
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
        - "8000:8000"
    # Control de consola:
    stdin_open: true
    tty: true
    
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: Prueba
      MYSQL_USER: magallanesa
      MYSQL_PASSWORD: an2101
      MYSQL_ROOT_PASSWORD: 12345678
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      PMA_HOST: db